import Footer from "./_lib/footer";
import Header from "./_lib/header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          <p>Header</p>
        </header> */}
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
